# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy to Production

on:
  push:
    tags:
      - "*"

env:
  TWILIO_PHONE_APP_NAME: onebusaway-twilio-webapp
  TWILIO_PHONE_IMAGE_NAME: nautilustechnologyau/transit/onebusaway-twilio-webapp
  TWILIO_SMS_APP_NAME: onebusaway-sms-webapp
  TWILIO_SMS_IMAGE_NAME: nautilustechnologyau/transit/onebusaway-sms-webapp
  ADMIN_APP_NAME: onebusaway-admin-webapp
  ADMIN_IMAGE_NAME: nautilustechnologyau/transit/onebusaway-admin-webapp
  ENTERPRISE_APP_NAME: onebusaway-enterprise-acta-webapp
  ENTERPRISE_IMAGE_NAME: nautilustechnologyau/transit/onebusaway-enterprise-acta-webapp
  SERVER_PORT: 8080
  LOCATION: 'Australia East'
  TIME_ZONE: 'Australia/Adelaide'

jobs:
  deploy_to_azure:
    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Twilio Phone Webapp to Azure Container Instances
        uses: azure/aci-deploy@v1.1.3
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ env.TWILIO_PHONE_APP_NAME }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.TWILIO_PHONE_IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: ${{ env.TWILIO_PHONE_APP_NAME }}
          ports: ${{ env.SERVER_PORT }}
          environment-variables: >
            TZ=${{ env.TIME_ZONE }}
            SERVER_PORT=${{ env.SERVER_PORT }}
            AZURE_COGNITIVE_SERVICE_URL=${{ secrets.AZURE_COGNITIVE_SERVICE_URL }}
            TRANSIT_DATA_SERVICE_URL=${{ secrets.TRANSIT_DATA_SERVICE_URL }}
            DATABASE_HOST=${{ secrets.TRANSIT_DATABASE_HOST }}
            DATABASE_PORT=${{ secrets.TRANSIT_DATABASE_PORT }}
            DATABASE_NAME=${{ secrets.TRANSIT_DATABASE_NAME }}
            DATABASE_USER=${{ secrets.TRANSIT_DATABASE_USER }}
          secure-environment-variables: >
            DATABASE_PASSWORD=${{ secrets.TRANSIT_DATABASE_PASSWORD }}
          location: ${{ env.LOCATION }}
          cpu: 1
          memory: 2

      - name: Deploy Twilio SMS Webapp to Azure Container Instances
        uses: azure/aci-deploy@v1.1.3
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ env.TWILIO_SMS_APP_NAME }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.TWILIO_SMS_IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: ${{ env.TWILIO_SMS_APP_NAME }}
          ports: ${{ env.SERVER_PORT }}
          environment-variables: >
            TZ=${{ env.TIME_ZONE }}
            SERVER_PORT=${{ env.SERVER_PORT }}
            TRANSIT_DATA_SERVICE_URL=${{ secrets.TRANSIT_DATA_SERVICE_URL }}
            DATABASE_HOST=${{ secrets.TRANSIT_DATABASE_HOST }}
            DATABASE_PORT=${{ secrets.TRANSIT_DATABASE_PORT }}
            DATABASE_NAME=${{ secrets.TRANSIT_DATABASE_NAME }}
            DATABASE_USER=${{ secrets.TRANSIT_DATABASE_USER }}
          secure-environment-variables: >
            DATABASE_PASSWORD=${{ secrets.TRANSIT_DATABASE_PASSWORD }}
          location: ${{ env.LOCATION }}
          cpu: 1
          memory: 2

      - name: Deploy Admin Webapp to Azure Container Instances
        if: github.ref != 'refs/heads/master'
        uses: azure/aci-deploy@v1.1.3
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ env.ADMIN_APP_NAME }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.ADMIN_IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: ${{ env.ADMIN_APP_NAME }}
          ports: ${{ env.SERVER_PORT }}
          environment-variables: >
            TZ=${{ env.TIME_ZONE }}
            SERVER_PORT=${{ env.SERVER_PORT }}
            TRANSIT_DATA_SERVICE_URL=${{ secrets.TRANSIT_DATA_SERVICE_URL }}
            DATABASE_HOST=${{ secrets.TRANSIT_DATABASE_HOST }}
            DATABASE_PORT=${{ secrets.TRANSIT_DATABASE_PORT }}
            DATABASE_NAME=${{ secrets.TRANSIT_DATABASE_NAME }}
            DATABASE_USER=${{ secrets.TRANSIT_DATABASE_USER }}
            APP_HOST_NAME=${{ secrets.TRANSIT_ADMIN_APP_HOSTNAME }}
            SERVER_URL=https://${{ secrets.TRANSIT_ADMIN_APP_HOSTNAME }}
          secure-environment-variables: >
            DATABASE_PASSWORD=${{ secrets.TRANSIT_DATABASE_PASSWORD }}
            GOOGLE_MAPS_API_KEY=${{ secrets.TRANSIT_GOOGLE_MAPS_API_KEY }}
            ADMIN_PASSWORD=${{ secrets.TRANSIT_ADMIN_PASSWORD }}
            OPERATOR_PASSWORD=${{ secrets.TRANSIT_OPERATOR_PASSWORD }}
          location: ${{ env.LOCATION }}
          cpu: 1
          memory: 2

      - name: Deploy Enterprise Webapp to Azure Container Instances
        if: github.ref != 'refs/heads/master'
        uses: azure/aci-deploy@v1.1.3
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ env.ENTERPRISE_APP_NAME }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.ENTERPRISE_IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: ${{ env.ENTERPRISE_APP_NAME }}
          ports: ${{ env.SERVER_PORT }}
          environment-variables: >
            TZ=${{ env.TIME_ZONE }}
            SERVER_PORT=${{ env.SERVER_PORT }}
            TRANSIT_DATA_SERVICE_URL=${{ secrets.TRANSIT_DATA_SERVICE_URL }}
            DATABASE_HOST=${{ secrets.TRANSIT_DATABASE_HOST }}
            DATABASE_PORT=${{ secrets.TRANSIT_DATABASE_PORT }}
            DATABASE_NAME=${{ secrets.TRANSIT_DATABASE_NAME }}
            DATABASE_USER=${{ secrets.TRANSIT_DATABASE_USER }}
            SIRI_BASE_URL=${{ secrets.TRANSIT_SIRI_BASE_URL }}
            API_BASE_URL=${{ secrets.TRANSIT_API_BASE_URL }}
            API_KEY=${{ secrets.TRANSIT_API_KEY }}
            XWIKI_URL=${{ secrets.TRANSIT_XWIKI_URL }}
          secure-environment-variables: >
            DATABASE_PASSWORD=${{ secrets.TRANSIT_DATABASE_PASSWORD }}
            GOOGLE_MAPS_API_KEY=${{ secrets.TRANSIT_GOOGLE_MAPS_API_KEY }}
            GOOGLE_GEOCODE_API_KEY=${{ secrets.TRANSIT_GOOGLE_GEOCODE_API_KEY }}
            XWIKI_USERNAME=${{ secrets.TRANSIT_XWIKI_USERNAME }}
            XWIKI_PASSWORD=${{ secrets.TRANSIT_XWIKI_PASSWORD }}
          location: ${{ env.LOCATION }}
          cpu: 1
          memory: 2
